### ISSUE TITLE
Check permissions async

### ISSUE THREAD

**Issue by SrBedrock** [GPAddons/GPClaimExpiration#19]
A Vault API request has been made on the main server thread that LuckPerms cannot safely respond to.

Error: https://haste.olziedev.com/raw/dosuyovaza

**Comment by Jikoo** [comment]
It's solveable, but a little bit annoying - Since we're using GP's event, we can't fire it asynchronously. Running permission checks async will also make things like the tamed pet ownership releasing less fluid - users will see GP's message about ownership even if the animal is released or transferred.

**Comment by Jikoo** [comment]
Should note - as a workaround you can either enable the config option for LP or remove perm nodes from GPCE's checks.
